### ISSUE TITLE
Could not find remote branch bug_15_fix to clone

### ISSUE THREAD

**Issue by simsketch** [antiguab/BAFluidView#20]
I'm trying to run pod install in my local directory for this app.

https://github.com/FancyPixel/gulps

My-Macbook:gulps-master-two username$ pod install
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `BAFluidView` from `https://github.com/antiguab/BAFluidView`, branch `bug_15_fix`

[!] Error installing BAFluidView
[!] /usr/bin/git clone https://github.com/antiguab/BAFluidView /var/folders/98/hsph0_wj4ll194qg8rr90ms40000gn/T/d20150720-1288-1wgijjp --single-branch --depth 1 --branch bug_15_fix

Cloning into '/var/folders/98/hsph0_wj4ll194qg8rr90ms40000gn/T/d20150720-1288-1wgijjp'...
warning: Could not find remote branch bug_15_fix to clone.
fatal: Remote branch bug_15_fix not found in upstream origin

Any ideas? Thanks!

**Comment by antiguab** [comment]
Ah! I removed this branched once I merged the bug #15 fix into master. I've made a PR to gulps with the version that has the [fix here](https://github.com/FancyPixel/gulps/pull/7). If you'd rather not wait, the fix is easy :) just change the `bug_15_fix` branch in the Podfile to `0.1.5`. Let me know how that goes!
